name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    buildType:
      description: 'Build config'
      required: true
      type: choice
      options:
        - Debug
        - Release
    branch:
      description: 'Target branch to build'
      default: 'master'
      required: false
      type: string

jobs:
  env-setup:
    runs-on: ${{ inputs.platform }}
    outputs:
      build: ${{steps.yeet.outputs.config}}

    steps:
      - name: Env setup
        run: echo "BUILD_TYPE=${{inputs.buildType}}" >> $GITHUB_ENV
        if: ${{contains(inputs.buildType, 'e')}}

      - name: Env setup - default
        run: echo "BUILD_TYPE=Release" >> $GITHUB_ENV
        if: ${{!contains(inputs.buildType, 'e')}}

      - name: Yeet outputs
        id: yeet
        run: echo "::set-output name=config::${{env.BUILD_TYPE}}"

      - name: Check outputs
        run: echo "BUILD_TYPE = |${{ steps.yeet.outputs.config }}|"

  build-ubuntu-latest:
    needs: [ env-setup ]
    uses: ./.github/workflows/cmake.yml
    with:
      platform: ubuntu-latest
      branch: ${{inputs.branch}}
      buildType: ${{steps.yeet.outputs.config}}

  build-windows-latest:
    needs: [ env-setup ]
    uses: ./.github/workflows/cmake.yml
    with:
      platform: windows-latest
      branch: ${{inputs.branch}}
      buildType: ${{steps.yeet.outputs.config}}